version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
